---
# tasks file for mysql-galera-setup
- name: "Check if mysql already installed"
  stat:
    path: "/etc/init.d/mysql"
  register:  mysql_init_present

- name: "Copy repos"
  template:
    src: galera.list.j2
    dest: /etc/apt/sources.list.d/galera.list

- name: "Pin reference to galera repo"
  template:
    src: galera.perf.j2
    dest: /etc/apt/preferences.d/galera.pref
    
- name: "Add signing key"
  command: "apt-key adv --keyserver keyserver.ubuntu.com --recv BC19DDBA"

- name: "Update cache"
  command: "sudo apt-get update --allow-insecure-repositories" 

- name: "Install package"
  apt:
      pkg:
        - galera-4
        - mysql-wsrep-8.0

- name: "Copy mysql config"
  template:
    src: mysql.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf 
